apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wul7f9vw6-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/wul7f9vw6-java-quarkus-gitops